export enum AITaskType {
  PRODUCT_UNDERSTANDING = 'PRODUCT_UNDERSTANDING',
  SEARCH_INTENT = 'SEARCH_INTENT',
  LEAD_RESEARCH = 'LEAD_RESEARCH',
  SALES_INTELLIGENCE = 'SALES_INTELLIGENCE',
  OUTREACH_GENERATION = 'OUTREACH_GENERATION',
}
